### ISSUE TITLE
New Integration // Drivly

### ISSUE THREAD

**Issue by nathanclevenger** [flethy/flethy#813]
- URL: https://driv.ly
- Docs: https://commerce.driv.ly - https://commerce.vin/#/paths/buyers/get
- Pricing: Free & Consumption Based
- Signup: https://driv.ly
- Social: https://twitter.com/drivly

**Comment by urbanisierung** [comment]
@nathanclevenger Awesome! Joined the waiting list, as soon as I get access I'll integrate with drivly. Looks very promising!
